apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: mariadb
spec:
  forProvider:
    chart:
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 13.1.3
    namespace: database-system
