apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: my-db-azure
  namespace: default
spec:
  parameters:
    storageGB: 20
    passwordSecretName: getting-started-db-pass
    class: small
  compositionSelector:
    matchLabels:
      uxp-guide: getting-started
      provider: azure
  writeConnectionSecretToRef:
    name: db-conn-azure
